server:
  port: 8081
  servlet:
    context-path: /auctionkoi

jwt:
  signerKey: ${SIGNER_KEY}

spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=AuctionKoi"
    username: sa
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        ddl-auto: update
        cache:
          use_second_level_cache: false
          format_sql: true
        naming:
          physical-strategy=org:
            hibernate:
              boot:
                model:
                  naming:
                      PhysicalNamingStrategyStandardImpl
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

#vnpay:
#  tmncode: QCYQY77A      # Mã sandbox mà VNPAY cung cấp
#  hashsecret: ST6Z81RWUFZMB7U2RAXO4Q5A3BXMZ68K  # Hash secret dùng để ký giao dịch
#  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html  # URL sandbox của VNPAY
#  returnurl: http://localhost:8081/auctionkoi/api/payment/vnpay-return  # URL callback để nhận phản hồi
#  spring.thymeleaf.cache=false
#  spring.thymeleaf.prefix=classpath:/templates/
#  spring.thymeleaf.suffix=.html


#  thymeleaf:
#    cache: false
#    prefix: /templates/
