server:
  port: 8081
  servlet:
    context-path: /auctionkoi

jwt:
  signerKey: "wxZ78Wi0+dAAbQLRRkt/c5gkT1t68h9/PucRFyJ3BZBryUdRsiObtjM2Q4Zn4HJ+"
#  signerKey: ${SIGNER_KEY}

spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=AuctionKoi"
    username: sa
    password: 12345
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    prefix: classpath:/templates/    # Thư mục chứa các file HTML
    suffix: .html                     # Phần mở rộng của file
    cache: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

vnpay:
  tmncode: QCYQY77A      # Mã sandbox mà VNPAY cung cấp
  hashsecret: ST6Z81RWUFZMB7U2RAXO4Q5A3BXMZ68K  # Hash secret dùng để ký giao dịch
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html  # URL sandbox của VNPAY
  returnurl: http://localhost:8081/auctionkoi/api/payment/vnpay-return  # URL callback để nhận phản hồi
