server:
  port: 8081
  servlet:
    context-path: /auctionkoi

jwt:
  signerKey: ${SIGNER_KEY}

spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=AuctionKoi"
    username: sa
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        ddl-auto: update
        cache:
          use_second_level_cache: false
          format_sql: true
        naming:
          physical-strategy=org:
            hibernate:
              boot:
                model:
                  naming:
                    PhysicalNamingStrategyStandardImpl
    show-sql: true

#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
##  thymeleaf:
##    prefix: classpath:/templates/    # Thư mục chứa các file HTML
##    suffix: .html                     # Phần mở rộng của file
##    cache: false
#
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.security: DEBUG
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.SQLServerDialect
#      ddl-auto: update
#      cache:
#        use_second_level_cache: false
#      format_sql: true
#  show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

vnpay:
  tmncode: ${TMN_CODE}                   # Merchant code provided by VNPAY
  hashsecret: ${HASH_SECRET}             # Secret key for data signing
  payurl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"   # Payment initiation URL
  returnurl: "/auctionkoi/vnpay/vnpay-payment-return"                   # Secret key for data signing

